project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "!slides/"
  resources:
    - "slides/"
    - "data/"
 
website:
  google-analytics: G-6LLMGL3T2Q
  title: "cours BIO4558"
  description: "Biostatistiques appliquées avec R"
  navbar:
    title: "BIO4558: cours"
    left:
      - text: Diapos
        href: lectures.qmd
      - text: Labo
        menu:
          - text: "Manuel"
            href:  https://biostats-uottawa.github.io/bio4558_manuel/
          - text: "Données"
            href: dataset.qmd
          - text: "Info suppl."
            href: practical_extra.qmd
      - text: "Syllabus"
        href: syllabus.qmd
      - text: Autres ressources
        menu:
          - text: Biostats uOttawa
            href: https://biostats-uottawa.github.io/
          - text: Biostats with R (Bio4158)
            href: https://biostats-uottawa.github.io/bio4158_course/
          - text: Advanced biostats and open science (Bio8940)
            href: https://biostats-uottawa.github.io/bio8940_course/
          - text: R-way to hell (R book)
            href: https://biostats-uottawa.github.io/R/en/
          - text: Chemin de l'enf-R (livre R)
            href: https://biostats-uottawa.github.io/R/fr/
    tools:
      - icon: envelope
        href: people.html
        text: Contact
      - icon: github
        menu:
        - text: Code
          href: https://github.com/biostats-uOttawa/bio4558_cours
        - text: Problèmes
          href: https://github.com/Biostats-uOttawa/bio4558_cours/issues

format:
  html:
    theme: 
      light: cosmo
      dark: [cosmo, css/theme-dark.scss]
    highlight: kate
    fig_align: center
    css: css/biostat.css
    toc: true
    lang: fr

